### ISSUE TITLE
localApi

### ISSUE THREAD

**Issue by yajiegithub** [DuendeSoftware/docs.duendesoftware.com#118]
![无标题](https://user-images.githubusercontent.com/35278902/158812550-9c6c4b94-8961-44a8-bee2-d0f799e86b31.png)

DuentityServer

    [Authorize(IdentityServerConstants.LocalApi.PolicyName)]
        public async Task<ActionResult<IEnumerable<FriendList>>> GetFriendLists()
        {           
            return (await _context.FriendLists.ToListAsync());
        }

BlazorSever
        public async Task<IActionResult> Get()
        {
            var token = await HttpContext.GetUserAccessTokenAsync();
            var client = new HttpClient();
            client.SetBearerToken(token);

            var response = await client.GetAsync($"https://localhost:5001/api/friends");

            return new JsonResult(await response.Content.ReadAsStringAsync());

        }

**Comment by brockallen** [comment]
The exception above is from your IdentityServer or your Blazor client app?

**Comment by yajiegithub** [comment]
we need some sample of  wasm‘s LocalApi......   ThankYou

**Comment by yajiegithub** [comment]
> The exception above is from your IdentityServer or your Blazor client app?

yes ,   wasm + B-server + duendity

**Comment by brockallen** [comment]
> we need some sample of wasm‘s LocalApi...... 

I'm unclear on what you're asking for. WASM runs in the client and we have samples using our BFF pattern here: 
https://docs.duendesoftware.com/identityserver/v6/samples/bff/

"LocalApi" is when you want to co-host an API with your IdentityServer (which would be a different host than your client apps):
https://docs.duendesoftware.com/identityserver/v6/apis/add_apis/

**Comment by yajiegithub** [comment]
please delete this issues，I solved it，I made a low-level mistake
