### ISSUE TITLE
Better menu scroll/focus 

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/docs.duendesoftware.com#13]
When you choose a menu item that's near the bottom of the scrolling menu, the currently selected page is no where to be seen. 

![image](https://user-images.githubusercontent.com/649492/103566787-a70f7f80-4e90-11eb-8c07-eca43a057751.png)

vs.

![image](https://user-images.githubusercontent.com/649492/103566799-abd43380-4e90-11eb-8b73-4bda3f37c3e0.png)

I'd like to get the menu to auto scroll to the current item when we load a page. This is low priority.

**Comment by ginazampino** [comment]
Ah, I see what you mean. I'm assuming this is because selecting a menu item reloads the whole website, resetting the scrollbar position. I'll look into it.
