### ISSUE TITLE
Sample HTML Not rendering in Client Notifications doc

### ISSUE THREAD

**Issue by markshaskins** [DuendeSoftware/docs.duendesoftware.com#136]
https://docs.duendesoftware.com/identityserver/v6/ui/logout/notification/#back-channel-server-side-clients

![image](https://user-images.githubusercontent.com/83560331/176098746-09823272-5716-4cac-9207-79b896ec7860.png)

In the actual markdown file I see this rendering as an iframe tag:
![image](https://user-images.githubusercontent.com/83560331/176098942-3caf540c-dd95-49f4-ac4a-1ee9cb8abd51.png)

**Comment by brockallen** [comment]
Thanks!
