### ISSUE TITLE
Server side Session store 

### ISSUE THREAD

**Issue by cdru** [DuendeSoftware/docs.duendesoftware.com#173]
The documentation for for [Server-Side Session Store](https://docs.duendesoftware.com/identityserver/v6/data/operational/sessions/) doesn't appear correct. It looks like it was started based on a copy of [Key Signing Store](https://docs.duendesoftware.com/identityserver/v6/data/operational/keys/) but only an initial "placeholder" version was pushed out.

**Comment by brockallen** [comment]
Ok thanks -- we'll check on it.
