### ISSUE TITLE
Not all options are fully documented

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/docs.duendesoftware.com#179]
We need to do a comparison. e.g. Options.

**Comment by josephdecock** [comment]
- [x] Authentication
- [x] Caching
- [ ] Ciba
- [ ] Cors
- [ ] Csp
- [ ] DeviceFlow
- [ ] Discovery
- [ ] DynamicProvider
- [ ] Endpoint
- [ ] Events
- [ ] IdentityServer
- [ ] InputLengthRestrictions
- [ ] KeyManagement
- [ ] Logging
- [ ] Mtls
- [ ] ServerSideSession
- [ ] UserInteraction
- [ ] Validation

**Comment by josephdecock** [comment]
Discovery needs to be documented

**Comment by brockallen** [comment]
PR merged -- is there more for this issue, or just some small things left?

**Comment by josephdecock** [comment]
Nothing is missing from the operational or configuration store options. Need to double check the BFF options, then we can close.
