### ISSUE TITLE
Documentation missing for why audience validation is disabled.

### ISSUE THREAD

**Issue by khayes** [DuendeSoftware/docs.duendesoftware.com#18]
https://docs.duendesoftware.com/identityserver/v5/quickstarts/1_client_credentials/

There is a note half down the page that is broken as it points to no reference
![image](https://user-images.githubusercontent.com/1069626/104843384-45083e80-58c2-11eb-9d9d-8f5c993cea42.png)

That is being generated at https://github.com/DuendeSoftware/docs.duendesoftware.com/blob/64ba7838e8ed16733b3eb77325b58e137d78c625/IdentityServer/v5/docs/content/quickstarts/1_client_credentials.md#L244 but from a quick search I can't see any reference that this should point to.

I gather the TODO discussion likely didn't happen and the document still got published. I'd suggest to just remove this note, but I'm unsure what you want to do here.

**Comment by leastprivilege** [comment]
fixed. thanks!
