### ISSUE TITLE
New section to discuss diff approaches to splitting UI and BFF hosts

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/docs.duendesoftware.com#227]
We see two main approaches: 
* CORS
* [Double] Reverse proxy

@pdevito3 has an article on the double reverse proxy approach: https://wrapt.dev/blog/standalone-duende-bff-for-any-spa
Our PR here shows the CORS approach: https://github.com/DuendeSoftware/Samples/pull/93

@josephdecock -- perhaps we should have docs that discuss pros/cons.

There's also a third approach with the `<base>` tag (which I've seen another customer use), but I don't know the details of mechanics (e.g. is CORS still involved).

Another question: will a remote API that emits a location header, for example, sill emit the correct host in the double reverse proxy approach? Maybe @pdevito3 knows?

**Comment by pdevito3** [comment]
Not sure offhand about the headers

**Comment by teate** [comment]
I want to say that this is greatly important topic. I know that there are many people, me included, that do want to keep their BFF logic and SPA logic completely separate. So I am urgently waiting for your solution proposal for this.

**Comment by leastprivilege** [comment]
Don't expect a "solution proposal". As always "it depends".

Either load your SPA from a "dummy" index.html from within the BFF host - or separate the BFF and SPA host.

**Comment by teate** [comment]
I must admit that I do not know what potential issues there are that need to be solved when separating the BFF and SPA host. For example:
1. Do I need a separate reverse proxy between the SPA and BFF, which "combines" those together? Or can I use the BFF's reverse proxy to achieve this?
2. What the reverse proxy should look like? Do I need to add some headers, CORS settings on the proxy?
3. Can I still use the SameSite cookie strict or does it become invalid if SPA and BFF are separated?
4. Is there any other technical challenges that I need to handle when SPA and BFF host are separated?

**Comment by leastprivilege** [comment]
OK - we will try to cover some pros and cons when we get to it.
