### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/docs.duendesoftware.com#359]
I think we should add a page to your docs called “Multi-Factor Authentication” - probably under user interaction / login where we 

* give reasoning why it is not included (see https://blog.duendesoftware.com/posts/20210520_custom_ui/)
* maybe give a couple of options (FIDO, aspnet identity, Google Authenticator)
* some more detailed links to the [ASP.NET](http://asp.net/) Identity docs covering MFA

**Comment by AndersAbel** [comment]
Fixed (I think) in #361, I just forgot to link this issue.

Do you have anything more to add?

**Comment by josephdecock** [comment]
Looks good, I just made a few edits in the follow up PR which can close this.
