### ISSUE TITLE
Update confusing wording V6 Docs for 6.x support for .NET 8

### ISSUE THREAD

**Issue by DanRogers99** [DuendeSoftware/docs.duendesoftware.com#381]
Version 6.x **is supported not supported** on .NET 8. 

https://github.com/DuendeSoftware/docs.duendesoftware.com/blob/5eba769800492b572c9df3928d525b25070d55e9/IdentityServer/v6/docs/content/_index.md?plain=1#L18

**Comment by brockallen** [comment]
Fixed, thanks.
