### ISSUE TITLE
Fix code on doc page for v7 quickstart 1 add-jwt-bearer-authentication

### ISSUE THREAD

**Issue by adhaliwal34** [DuendeSoftware/docs.duendesoftware.com#423]
[page here](https://docs.duendesoftware.com/identityserver/v7/quickstarts/1_client_credentials/#add-jwt-bearer-authentication)
```
options.TokenValidationParameters = false;
```
should be
```
options.TokenValidationParameters.ValidateAudience = false;
```

To match the v7 quickstarts code repo [here](https://github.com/DuendeSoftware/Samples/blob/main/IdentityServer/v7/Quickstarts/1_ClientCredentials/src/Api/Program.cs).

It's a compiler error currently.

**Comment by josephdecock** [comment]
Thanks again for catching these!
