### ISSUE TITLE
Fix Visual studio set up instruction on v7 quickstarts 1 page

### ISSUE THREAD

**Issue by adhaliwal34** [DuendeSoftware/docs.duendesoftware.com#424]
[On this page](https://docs.duendesoftware.com/identityserver/v7/quickstarts/1_client_credentials/#calling-the-api)

The text `Start New Instance` should be `Start Without Debugging` so that the window stays open and we can see the output. Tested on Visual Studio 2022.

**Comment by josephdecock** [comment]
Thanks for pointing this out!
