### ISSUE TITLE
More explicit refresh token topics

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/docs.duendesoftware.com#57]
We might need some more explicit discussion of refresh tokens in our docs. How to configure on Client and that it's not needed in Scopes config, and how to request w/ offline_access.

**Comment by leastprivilege** [comment]
I re-read 

https://docs.duendesoftware.com/identityserver/v5/tokens/refresh/

It has all in there. Any specific ideas?

**Comment by brockallen** [comment]
I guess that has it all. This was raised by a discussion thread that missed the concepts of AllowOfflineAccess and the corresponding scope.
