### ISSUE TITLE
AKV-managed token signing cert app settings config

### ISSUE THREAD

**Issue by guardrex** [DuendeSoftware/docs.duendesoftware.com#66]
Forgive me for the 📘 here 🙈😄. I'd like to explain this scenario out a bit before asking my questions ...

An ASP.NET Core Blazor doc maintains guidance for a hosted Blazor WebAssembly app using IdS on Windows App Service using an AKV-managed IdS token signing certificate. The guidance calls for the developer to:

* Set an Azure App Service setting of `WEBSITE_LOAD_CERTIFICATES` with the cert thumbprint.
* Supply app settings for Identity Server (not necessarily Duende IdS) that taps the **CurrentUser** > **My** cert store.

  ```json
  "IdentityServer": {
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "CurrentUser",
      "Name": "CN=IdentityServerSigning"
    }
  }
  ```

We're trying to keep token signing cert access simple, clear, and 🔐 **_SAFE_** 🔐. A reader has remarked that such an IdS app config isn't viable for **_Linux_** App Service scenarios.

In passing, alternatives to that approach might include:

* Loading a cert manually (*as a secret*) from AKV (`KeyVaultClient`) and calling `AddSigningCredential`.
* Some alternate flavor of that via an `X509Store` with `AddSigningCredential`, hopefully with `FindByThumbprint`.

However, those approaches would be more complex and require more developer code.

Our doc section ...

https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-identity-server?view=aspnetcore-5.0&tabs=visual-studio#host-in-azure-app-service-with-a-custom-domain-and-certificate-1

We're leaning here toward accessing whatever Linux considers its cert storage along the lines of https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs#L101-L112.

... and perhaps that approach calling `AddSigningCredential` will turn out to be the best practices way to go. Perhaps, Duende API  doesn't read app settings for a cert store into a call to `AddSigningCredential` for the dev. Perhaps, the dev just needs to handle this in their own code.

After digging around a bit, it feels like **CurrentUser** > **My** would be a thing on Linux. For example ...

https://docs.microsoft.com/en-us/dotnet/standard/security/cross-platform-cryptography#the-my-store

A reader working with Linux App Service has suggested a working approach where the physical location of where the cert loads is specified in app configuration ...

```json
{
  "IdentityServer": {
    "Key": {
      "Type": "File",
      "FilePath": "/var/ssl/private/{thumbprintGoesHere}.p12",
      "Password": ""
    }
  }
}
```

Again, the preceding may or may not be viable for Duende IdS.

Cross-reference: https://github.com/dotnet/AspNetCore.Docs/issues/23180#issue-984245605

Physical paths are fragile in general, sometimes poorly supported and/or documented, sometimes not the same distro-to-distro. Of greater concern to me is that "**_Password_**" entry in app settings config ... even with a blank value ... **_Yikes!_** 😨🏃. Truly, I'd rather pitch an approach using a Key Vault Client over using that app settings config.

So ... the ❓s ... sorry that it took so long to get here 😅.

Duende IdS **_with_** the token signing cert in AKV **_with_** Azure App Service ...

* Our doc wasn't written with Duende IdS in mind.
  * Is the **_Windows_** App Service configuration (the **CurrentUser** > **My** cert store app config) the same for Duende IdS?
  * If not, should the dev to call `AddSigningCredential` with a `StoreLocation` (**CurrentUser**/**My**? or a different store) and `NameType` (cert thumbprint)?
  * If not, would you next suggest an AKV client (cert loaded as a *secret* perhaps)+`AddSigningCredential`-based approach?
* The Duende docs don't cover the best practice configuration/set up explicitly for these scenarios, Windows or Linux App Service with AKV. Do you want to cover it so that the Blazor WASM doc can link to a Duende doc for this scenario? Alternatively, can you comment on the best practices approach so that I can place your recommendation into the Blazor WASM topic? ... and as mentioned, I need **_Windows_**- and **_Linux_**-based guidance.

**Comment by brockallen** [comment]
I'm overloaded by the question, so I'll *try* to rephrase and you tell us if I got it right. You're asking: "Does Duende IdentityServer come with a way to load signing credentials from AKV?".

If you want to use a cert and you're on a windows based host, then yes you can use the "My" store mapping magic. But if you're on linux then you'd just call the AKV APIs to load the credential. 

I don't think we should tell you which way is the the right way, as it depends. We are a framework and allow a variety of approaches. But if I had to tell you one and only one way, then I'd remind you that we have [automatic signing credentials](https://docs.duendesoftware.com/identityserver/v5/fundamentals/keys/#automatic-key-management) built in, and that's protected with ASP.NET Data Protection. And you would then protect the Data Protection keys with AKV.

**Comment by guardrex** [comment]
*Yes* ... sorry for the overload there. *Yes* ... loading signing credentials from AKV **by certificate** for Windows and Linux App Service scenarios.

> But if you're on linux then you'd just call the AKV APIs to load the credential.

Perfect ... that's what it looked like from my research for this scenario. It's easy to set up, well documented, and **_SAFE_** 🔐😅. 

> We are a framework and allow a variety of approaches. 

That's cool. This would be specifically for a cert stored in Azure Key Vault, which seems specific enough to offer specific guidance (or specific cross-links to existing guidance). However, it might be a scenario that could be covered by naming **_briefly_** (with cross-links, perhaps) a few common, supported approaches.

> automatic signing credentials built in

Perfect, yes ... that's just something that I personally haven't tested. I'll confer with the reader on it. I'd like to see if they chose the certificate route merely because our doc suggested it or if they had a specific reason not to use the automatic signing credentials.

**_I'm good._** :+1: Thanks for your help, @brockallen! :beers:

**Comment by brockallen** [comment]
And to summarize, none of this has anything to do with IdentityServer. :)

My sense is that your complaint is that in Windows Azure things feel slightly easier than Linux Azure (at least with respect to the "My" mapping feature). And of course, it's the same complaint if you're asking for certs for protecting IdentityServer or for certs for protecting ASP.NET Core Data Protection.

**Comment by guardrex** [comment]
I wouldn't describe my issue as a "complaint." I'm just asking a question. I'm not experienced with IdS ... or Linux for that matter. We're often called upon to document technology integrations that we aren't familiar with, so we need to ask basic questions from time-to-time, perhaps kind'a dumb questions :smile:. The app configuration key `IdentityServer` > `Key` implies that these are integrated concepts. If that's DP/ASP.NET Core framework-enabled configuration that has nothing to do directly with IdS, ok ... I hear u on that.

I think I have what I need for a supported scenario: automatic signing credentials (on by default; cross-link to the doc over here) with keys protected by DP-AKV (`ProtectKeysWithAzureKeyVault`; cross-link to our DP coverage on that). I'll keep the Windows coverage just in case. That was requested by our readers. It's TBD on other scenarios, such as Key Vault Client with a cert for Linux. I'll have to consider that aspect further when I reach the issue.

Thanks again for your help. Much appreciated!
