### ISSUE TITLE
Add migration docs for MS template to Duende

### ISSUE THREAD

**Issue by leastprivilege** [DuendeSoftware/docs.duendesoftware.com#67]

**Comment by leastprivilege** [comment]
we need this...

**Comment by brockallen** [comment]
Ok, this will be involved. Some of the things we need to cover:

* decide if we want IS co-hosted or separate host
* replace the MS NuGet with ours
* replace AddApiAuthorization on IdentityServerBuilder with:
   * configure the cookie scheme explicitly if co-hosted
   * operational store on the ApplicationDbContext defined in the template
   * AddAspNetIdentity on the ApplicationUser defined in the template
   * our in-mem clients & scopes. do we need to support their json config, or use our standard approach?
   * add the template name as a client ("{ProjectName}") and a scope ("{ProjectName}API")
   * do we need to migrate/support their signing keys?
* replace AddIdentityServerJwt on AuthenticationBuilder with:
   * something that can handle both JWT and cookies dynamic based on path (e.g. "/Identity" using ForwardDefaultSelector?) if we co-host
   * JWT auth handler (maybe with scheme "IdentityServerJwtBearer"). do we use our co-hosted or normal JWT bearer if not co-hosted
   * do we add a authZ policy for scope validation (the MS template uses "aud" in the JWT bearer validator)
* decide how much of the SPA dynamic registration is to be used, or do we adjust the manifest.json to contain the config for oidc-client-js

So all in all, there needs to be a design here, IMO.

**Comment by brockallen** [comment]
Done
