### ISSUE TITLE
BFF docs feedback

### ISSUE THREAD

**Issue by brockallen** [DuendeSoftware/docs.duendesoftware.com#72]
Placeholder to collect feedback while reviewing

* Personal opinion: the intro is too casual
* There's some copy editing that could be done throughout
   * some sections need more context to intro them
   * some topics need expanded explanation of what it's referring to (e.g. "the endpoints that want the extra security must be decorated" -- what that referrs to should be clarified)
* Session mgmt endpoints should explain request style of each: Ajax vs. browser redirect
* need formal docs on the EF support
* ~~missing page for session mgmt details~~

**Comment by leastprivilege** [comment]
@josephdecock could you give that some "native speaker" treatment?

**Comment by brockallen** [comment]
Done
