### ISSUE TITLE
InvalidOperationException: No signing credential is configured.

### ISSUE THREAD

**Issue by murphymj5209** [DuendeSoftware/docs.duendesoftware.com#8]
I am getting an error message : InvalidOperationException: No signing credential is configured. when doing the Quickstart 1 & 2.  Please let me know what is the problem.
[screencapture-demo-duendesoftware-connect-authorize-callback-2020-11-15-13_58_01.pdf](https://github.com/DuendeSoftware/docs.duendesoftware.com/files/5543043/screencapture-demo-duendesoftware-connect-authorize-callback-2020-11-15-13_58_01.pdf)

**Comment by leastprivilege** [comment]
Hi, 

you might use an older version - please make sure you are using preview.1.6

https://www.nuget.org/packages/Duende.IdentityServer/5.0.0-preview.1.6
