### ISSUE TITLE
Redundant  `options.Scope.Add("profile")`

### ISSUE THREAD

**Issue by AndersAbel** [DuendeSoftware/docs.duendesoftware.com#94]
In QS2, in the section about the UserInfo endpoint, the OIDC config in the MvcApp is updated with `options.Scope.Add("profile");` That is redundant, as the profile scope is already added by default by the OIDC handler:

https://github.com/dotnet/aspnetcore/blob/15fa3ad10859abcc54e3ad5557dc928f6c94994d/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectOptions.cs#L44

I think the redundant line should be removed, but probably text should also be updated to notice that the results retrieved from the user info endpoint are those for the open_id and profile scopes.

**Comment by leastprivilege** [comment]
I would even do a `scope.Clear()` and then add the `openid` and `profile` - I am really not a fan of the default value.
