### ISSUE TITLE
Compile error in quickstart

### ISSUE THREAD

**Issue by Vizual-Dev** [DuendeSoftware/docs.duendesoftware.com#99]
The "Interactive Applications with ASP.NET Core" quickstart reports a compile error on the "Display the Auth Cookie" step.

The file name is also a bit jumbled, it says "geWebClient/Pas/Index.cshtml" instead of "WebClient/Pages/Index.cshtml"

The issue is in the loop to display the claims, it says:

"The name 'Context' does not exist in the current context"

Looking at the source code for the quick start it should be HttpContext.AuthenticateAsync() instead of Context.AuthenticateAsync()

**Comment by josephdecock** [comment]
Thanks for the bug report!
